sudo: required
services:
  - docker
before_install:
  - docker pull yshalsager/lineageos:14.1
before_script:
  - cd $HOME && mkdir twrp
  - wget -q https://github.com/TwrpBuilder/twrp-sources/releases/download/omni_twrp-8.1-20180221-norepo/omni_twrp-8.1-20180221-norepo.tar.xz
    -O $HOME/twrp.tar.xz
  - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
  - cd $HOME/twrp/ && git clone https://github.com/ananjaser1211/android_device_samsung_treltexx.git device/samsung/treltexx
  - rm -rf prebuilts/clang/host/linux-x86 && git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 prebuilts/clang/host/linux-x86 -b android-7.0.0_r21 --depth=1
  - rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery --depth=1
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/home/twrp/:rw,z" yshalsager/lineageos:14.1 bash << EOF
    cd /home/twrp/
    source build/envsetup.sh && lunch omni_treltexx-eng && make -j16 recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - echo -n "SEANDROIDENFORCE" >> "$HOME/twrp/out/target/product/treltexx/recovery.img"
  - cp $HOME/twrp/out/target/product/treltexx/recovery.img $HOME/twrp/TWRP-$version-treltexx-$(date +"%Y%m%d").img
  - cd $HOME/twrp/out/target/product/treltexx/
  - tar -cf recovery.tar recovery.img
  - cp recovery.tar $HOME/twrp/TWRP-$version-treltexx-$(date +"%Y%m%d").tar


deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_TB"
  file_glob: true
  file: $HOME/twrp/TWRP-*
  on:
    tags: false
    repo: ananjaser1211/android_device_samsung_treltexx
    branch: twrp-7.1
branches:
  except:
    - /^(?i:untagged)-.*$/
